version: '3.5'

services:
  hbbs:
    container_name: rustdesk_hbbs
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r $HOSTNAME:21117 -k _
    volumes:
      - rustdesk_data:/root
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: rustdesk_hbbr
    ports:
      - 21117:21117
      - 21119:21119
    image: rustdesk/rustdesk-server:latest
    command: hbbr -k _
    volumes:
      - rustdesk_data:/root
    restart: unless-stopped

volumes:
  rustdesk_data:
    external: true

networks:
  default:
    name: rustdesk_subnet
